#!/bin/bash
# Copyright (C) 2014 The Android Open Source Project
# Copyright (C) 2017 dady8889@github

# Device, vendor variables needed for path
DEVICE=hi6250
VENDOR=huawei

# Input, output
INPUT=device-proprietary-files.txt
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=device-vendor.mk

echo "Generating vendor blobs makefile..."

# License
YEAR=`date +"%Y"`
(cat << EOF) > $MAKEFILE
# Copyright (C) $YEAR The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was automatically generated by setup_blobs.sh

PRODUCT_COPY_FILES += \\
EOF

# Line count, filter empty spaces and comments
PROGRESS=0
LINEEND=" \\"
COUNT=`wc -l $INPUT | awk {'print $1'}`
DISM=`egrep -c '(^#|^$)' $INPUT`
COUNT=`expr $COUNT - $DISM`
PROGRESSCOUNT=$COUNT

# Iterate each line
for FILE in `egrep -v '(^#|^$)' $INPUT`; do
  COUNT=`expr $COUNT - 1`

  if [ $COUNT = "0" ]; then
    LINEEND=""
  fi

  # Split the file from the destination (format is "file[:destination]")
  OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
  if [[ ! "$FILE" =~ ^-.* ]]; then
    FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
    DEST=${PARSING_ARRAY[1]}
    if [ -n "$DEST" ]; then
        FILE=$DEST
    fi
    echo "    $OUTDIR/$FILE:system/$FILE$LINEEND" >> $MAKEFILE
  fi

  # Show progress
  PROGRESS=$((PROGRESS+1))
  echo -ne "\033[K[$PROGRESS/$PROGRESSCOUNT] $FILE\r"
done

echo "[$PROGRESSCOUNT/$PROGRESSCOUNT] $MAKEFILE was successfully generated!"
